#db-config
spring.datasource.url=jdbc:postgresql://localhost:5432/authorization_server
spring.datasource.username=postgres
spring.jpa.show-sql=true

#redrectUris
issueruri=http://localhost:8180

#Temporary settings
logging.level.web=INFO
logging.level.org.springframework.security=INFO




