# auth-server-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: secret-name
type: Opaque
data:
  spring.datasource.password: cGFzc3dvcmQ= # Base64 encoded password
  key : a2V5 # Base64 encoded key
  spring.mail.password: cGFzc3dvcmQ= # Base64 encoded password

